"""
The Desktop shortcut — a double-clickable "VetClinicSystem JO" icon that
starts the app correctly no matter what has happened since it was created:
updates that replaced the whole codebase, a shutdown, a restart, or an
autostart registration that silently stopped working.

It is deliberately a *dumb pointer at the supervisor launcher*, never at a
release folder. `vetclinicsystemjo-data/Start VetClinicSystem JO.command`
is the one launcher that re-reads `active_release.txt` on every start, so
pointing at it is what makes this survive updates — the same reasoning
autostart.py's managed_data_dir() exists for, and the same trap (pinning
to whichever code copy happened to be current at creation time) avoided the
same way.

Created by setup.py once the versioned-release layout exists, and
re-created idempotently on every later setup.py run, so a shortcut someone
dragged to the Trash comes back rather than needing a hand-written
replacement.

macOS: a real .app bundle on the Desktop, so it can carry the clinic icon
(Finder only reads an icon from a bundle's Info.plist — a bare .command
file has nowhere to put one). Its executable is a small shell script that
opens the supervisor launcher in Terminal, exactly as double-clicking the
launcher itself would.
Windows: a .lnk shortcut with IconLocation set, created through the same
WScript.Shell COM object Explorer itself uses, so no pywin32 dependency.
Anything else: not supported, same as autostart.py.
"""
import os
import platform
import plistlib
import shutil
import stat
import subprocess

import autostart

APP_NAME = "VetClinicSystem JO"
BUNDLE_ID = "com.vetclinicsystemjo.desktop"
LAUNCHER_BASENAME = "Start VetClinicSystem JO"
DEFAULT_PORT = "5050"
BASE_DIR = os.path.dirname(os.path.abspath(__file__))


def is_supported():
    return platform.system() in ("Darwin", "Windows")


def _icon_path(suffix):
    """The committed icon asset for this platform. Lives in the codebase (so
    it ships with every release) and gets copied out to the Desktop bundle /
    data dir at creation time."""
    return os.path.join(BASE_DIR, "installer_assets", f"appicon.{suffix}")


def _resolve_data_dir(data_dir=None):
    """Where the supervisor launcher lives. Callers that already know (setup.py
    right after writing it) pass it in; everything else re-derives it the same
    way autostart does."""
    return data_dir or autostart.managed_data_dir()


def _macos_bundle_path():
    return os.path.expanduser(f"~/Desktop/{APP_NAME}.app")


def _windows_desktop_candidates():
    """Windows Desktop is not reliably ~/Desktop — OneDrive's "back up your
    folders" moves it. Check the redirected location first, since that's the
    one that's actually on screen when it exists."""
    profile = os.environ.get("USERPROFILE")
    if not profile:
        return []
    candidates = []
    onedrive = os.environ.get("OneDrive") or os.path.join(profile, "OneDrive")
    candidates.append(os.path.join(onedrive, "Desktop"))
    candidates.append(os.path.join(profile, "Desktop"))
    return [c for c in candidates if os.path.isdir(c)]


def _windows_shortcut_paths():
    return [os.path.join(d, f"{APP_NAME}.lnk") for d in _windows_desktop_candidates()]


def is_present():
    system = platform.system()
    if system == "Darwin":
        return os.path.isdir(_macos_bundle_path())
    if system == "Windows":
        return any(os.path.isfile(p) for p in _windows_shortcut_paths())
    return False


def create(data_dir=None):
    system = platform.system()
    if system == "Darwin":
        return _macos_create(data_dir)
    if system == "Windows":
        return _windows_create(data_dir)
    return False, "Desktop shortcuts aren't supported on this operating system."


def remove():
    system = platform.system()
    if system == "Darwin":
        return _macos_remove()
    if system == "Windows":
        return _windows_remove()
    return False, "Desktop shortcuts aren't supported on this operating system."


# ---------------------------------------------------------------------------
# macOS
# ---------------------------------------------------------------------------

# Kept as a template rather than built by string-concatenation so the quoting
# is readable: every interpolated path goes in through %r-style shell quoting
# at format time (see _macos_create), never raw.
_MACOS_LAUNCH_SCRIPT = """#!/bin/bash
# Generated by VetClinicSystem JO's setup — do not edit by hand; re-running
# setup.py rewrites this file.
#
# Points at the supervisor launcher in the data folder, NOT at any
# vetclinicsystemjo-releases/app_vX.Y.Z/ copy, so updates never strand it.
set -u
LAUNCHER={launcher}
PORT="${{VETCLINICSYSTEMJO_PORT:-{port}}}"
URL="http://127.0.0.1:$PORT"

# Already up? Just show it. A Desktop icon gets double-clicked whenever
# someone wants the app in front of them, which is not the same thing as
# wanting a second copy of it started.
if /usr/bin/curl -fsS -m 2 "$URL/health" >/dev/null 2>&1; then
  /usr/bin/open "$URL"
  exit 0
fi

if [ ! -f "$LAUNCHER" ]; then
  /usr/bin/osascript -e 'display alert "VetClinicSystem JO" message "This shortcut can no longer find the app. If the app folder was moved or renamed, run setup.py again from the new location to rebuild it." as critical'
  exit 1
fi

exec /usr/bin/open -a Terminal "$LAUNCHER"
"""


def _macos_create(data_dir=None):
    data_dir = _resolve_data_dir(data_dir)
    if not data_dir:
        return False, ("Automatic updates aren't set up on this install yet, so there's no "
                       "update-proof launcher for a shortcut to point at. Run setup.py first.")
    launcher = os.path.join(data_dir, f"{LAUNCHER_BASENAME}.command")
    if not os.path.isfile(launcher):
        return False, f"Could not find the launcher at {launcher} — can't create the Desktop shortcut."

    icon_src = _icon_path("icns")
    bundle = _macos_bundle_path()
    macos_dir = os.path.join(bundle, "Contents", "MacOS")
    resources_dir = os.path.join(bundle, "Contents", "Resources")

    try:
        # Replaced wholesale rather than patched in place: an older bundle may
        # point at a path that no longer exists (install moved), and a partial
        # overwrite would leave the stale executable behind.
        if os.path.isdir(bundle):
            shutil.rmtree(bundle)
        os.makedirs(macos_dir, exist_ok=True)
        os.makedirs(resources_dir, exist_ok=True)

        script_path = os.path.join(macos_dir, "launch")
        with open(script_path, "w", newline="\n") as f:
            f.write(_MACOS_LAUNCH_SCRIPT.format(
                launcher=_sh_quote(launcher), port=DEFAULT_PORT))
        os.chmod(script_path, os.stat(script_path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

        if os.path.isfile(icon_src):
            shutil.copy(icon_src, os.path.join(resources_dir, "appicon.icns"))

        info = {
            "CFBundleName": APP_NAME,
            "CFBundleDisplayName": APP_NAME,
            "CFBundleIdentifier": BUNDLE_ID,
            "CFBundleExecutable": "launch",
            "CFBundleIconFile": "appicon",
            "CFBundlePackageType": "APPL",
            "CFBundleInfoDictionaryVersion": "6.0",
            "CFBundleShortVersionString": "1.0",
            "CFBundleVersion": "1.0",
            "NSHighResolutionCapable": True,
            # Nothing here draws its own window — the app itself is a browser
            # page and the launcher runs in Terminal — so keep it out of the
            # Dock and the app switcher.
            "LSUIElement": True,
        }
        with open(os.path.join(bundle, "Contents", "Info.plist"), "wb") as f:
            plistlib.dump(info, f)

        # Finder caches an icon per bundle path; without a mtime bump it can
        # keep showing the generic app icon for a bundle it has seen before.
        subprocess.run(["touch", bundle], capture_output=True, text=True)
    except OSError as e:
        return False, f"Could not create the Desktop shortcut: {e}"
    return True, f"Desktop shortcut created — “{APP_NAME}” on your Desktop."


def _sh_quote(value):
    """Single-quote a path for safe embedding in the generated bash script."""
    return "'" + str(value).replace("'", "'\"'\"'") + "'"


def _macos_remove():
    bundle = _macos_bundle_path()
    if not os.path.isdir(bundle):
        return True, "There's no Desktop shortcut to remove."
    try:
        shutil.rmtree(bundle)
    except OSError as e:
        return False, f"Could not remove the Desktop shortcut: {e}"
    return True, "Desktop shortcut removed."


# ---------------------------------------------------------------------------
# Windows
# ---------------------------------------------------------------------------

def _windows_create(data_dir=None):
    data_dir = _resolve_data_dir(data_dir)
    if not data_dir:
        return False, ("Automatic updates aren't set up on this install yet, so there's no "
                       "update-proof launcher for a shortcut to point at. Run setup.py first.")
    launcher = os.path.join(data_dir, f"{LAUNCHER_BASENAME}.bat")
    if not os.path.isfile(launcher):
        return False, f"Could not find the launcher at {launcher} — can't create the Desktop shortcut."

    # The .ico is copied next to the launcher rather than referenced inside the
    # release folder: a .lnk stores an absolute icon path, and release folders
    # get pruned two updates later, which would leave the shortcut iconless.
    icon_dest = os.path.join(data_dir, "appicon.ico")
    icon_src = _icon_path("ico")
    try:
        if os.path.isfile(icon_src):
            shutil.copy(icon_src, icon_dest)
    except OSError:
        icon_dest = None

    # [Environment]::GetFolderPath('Desktop') is the only reliable way to get
    # the real Desktop — it follows OneDrive/Known Folder redirection, which
    # %USERPROFILE%\Desktop does not.
    ps = (
        "$ErrorActionPreference='Stop';"
        "$desktop=[Environment]::GetFolderPath('Desktop');"
        f"$lnk=Join-Path $desktop '{APP_NAME}.lnk';"
        "$s=(New-Object -ComObject WScript.Shell).CreateShortcut($lnk);"
        f"$s.TargetPath={_ps_quote(launcher)};"
        f"$s.WorkingDirectory={_ps_quote(data_dir)};"
        f"$s.Description={_ps_quote(APP_NAME)};"
    )
    if icon_dest:
        ps += f"$s.IconLocation={_ps_quote(icon_dest)};"
    ps += "$s.Save();Write-Output $lnk"

    try:
        result = subprocess.run(
            ["powershell", "-NoProfile", "-NonInteractive", "-Command", ps],
            capture_output=True, text=True,
        )
    except OSError as e:
        return False, f"Could not create the Desktop shortcut: {e}"
    if result.returncode != 0:
        return False, f"Could not create the Desktop shortcut: {(result.stderr or '').strip()}"
    return True, f"Desktop shortcut created — “{APP_NAME}” on your Desktop."


def _ps_quote(value):
    """Single-quote a value for a PowerShell literal string."""
    return "'" + str(value).replace("'", "''") + "'"


def _windows_remove():
    paths = [p for p in _windows_shortcut_paths() if os.path.isfile(p)]
    if not paths:
        return True, "There's no Desktop shortcut to remove."
    for path in paths:
        try:
            os.remove(path)
        except OSError as e:
            return False, f"Could not remove the Desktop shortcut: {e}"
    return True, "Desktop shortcut removed."
