-- VetClinicSystem JO database schema — v3 (PostgreSQL)
-- Ported from the original SQLite schema.sql. Table/column names, types,
-- and constraints are unchanged except: AUTOINCREMENT -> IDENTITY, and
-- REAL -> DOUBLE PRECISION (same practical behavior, more standard on PG).
--
-- Currency precision: unlike VetClinicSystem_IQ (Iraq — IQD's fils
-- subunit is practically obsolete, every real amount is a whole number,
-- so double-precision float loses nothing), the Jordanian Dinar is one
-- of three currencies worldwide (with KWD/BHD) that ISO 4217 assigns
-- 3 decimal places — the fils subunit is in everyday real use here,
-- and float64 cannot exactly represent most 3-decimal fractions
-- (0.1 + 0.2 != 0.3 in binary floating point). Every column that holds
-- a currency amount, or a quantity that gets multiplied directly
-- against one (so it must be the same numeric type to avoid a Python
-- Decimal/float TypeError — see parse_money() in app.py), is declared
-- NUMERIC here instead of DOUBLE PRECISION: NUMERIC(12,3) for money,
-- NUMERIC(10,3) for those quantities, NUMERIC(5,2) for discount_percent
-- (also multiplied directly against a money subtotal). Physical
-- measurements (weight_kg), inventory-count-only fields never
-- multiplied against a price (stock_counted, received_since_prior,
-- reorder_threshold, target_coverage_days, change_qty), and BCS stay
-- DOUBLE PRECISION/INTEGER — they're not currency and never mix with
-- Decimal arithmetic.

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- Atomic ID-allocation counters (P001, V002, IC003, ...). Replaces the old
-- MAX(id)+1-in-Python approach, which was not safe under concurrent use.
CREATE TABLE IF NOT EXISTS id_counters (
    prefix TEXT PRIMARY KEY,
    next_val INTEGER NOT NULL DEFAULT 1
);

-- History of nightly/manual database backups, shown in Settings.
CREATE TABLE IF NOT EXISTS backup_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TEXT NOT NULL,
    finished_at TEXT,
    status TEXT NOT NULL CHECK (status IN ('running','success','failed')),
    filepath TEXT,
    filesize_bytes BIGINT,
    error TEXT
);
CREATE INDEX IF NOT EXISTS idx_backup_log_started ON backup_log(started_at);


-- ============================================================ AUTH / USERS
CREATE TABLE IF NOT EXISTS roles (
    id TEXT PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    discount_cap INTEGER NOT NULL DEFAULT 0 CHECK (discount_cap BETWEEN 0 AND 100),
    -- Whether staff with this role can be assigned as the attending vet
    -- (Appointments grid, New Visit, Grooming, Inpatient) — a role
    -- attribute rather than a hardcoded role NAME check, so renaming or
    -- restructuring the "Vet" role can't silently empty every vet picker.
    is_vet_role BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL
);

-- Static seed list of every permission key the app understands — not
-- admin-editable itself, just the fixed vocabulary of what *can* be gated.
-- Kept in sync with auth.PERMISSIONS on every launch.
CREATE TABLE IF NOT EXISTS permissions (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    category TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id TEXT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id TEXT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT NOT NULL,
    role_id TEXT NOT NULL REFERENCES roles(id),
    custom_discount_cap INTEGER CHECK (custom_discount_cap BETWEEN 0 AND 100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    -- Bumped every time this user's password_hash changes (self-service or
    -- admin reset). Stashed in the session at login and compared on every
    -- request (see require_login() in app.py) — a session logged in before
    -- the most recent change is invalidated, so a stolen cookie stops
    -- working the moment the password it was issued under is replaced,
    -- instead of staying valid for the rest of its normal lifetime.
    password_changed_at TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role_id);

CREATE TABLE IF NOT EXISTS login_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    username TEXT,
    success INTEGER NOT NULL,
    timestamp TEXT NOT NULL,
    ip TEXT,
    user_agent TEXT
);

CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    username TEXT,
    timestamp TEXT NOT NULL,
    action TEXT NOT NULL,          -- 'create' / 'update' / 'delete'
    table_name TEXT NOT NULL,
    record_id TEXT NOT NULL,
    field TEXT,
    old_value TEXT,
    new_value TEXT
);
CREATE INDEX IF NOT EXISTS idx_audit_ts ON audit_log(timestamp);

-- ============================================================ OWNERS / PATIENTS
CREATE TABLE IF NOT EXISTS owners (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    notes TEXT
);
-- Nothing in the app looked up an existing owner by phone before
-- inserting a new one, so re-entering an existing owner's info (e.g. from
-- the "new patient" visit form) or double-submitting the new-owner form
-- silently created a duplicate row instead of failing or linking to the
-- existing owner. A plain UNIQUE index on a nullable column allows any
-- number of owners with no phone on file (each NULL is distinct in
-- Postgres) while rejecting a second owner with the same phone outright —
-- app.py's owner_new()/visit_new_patient() catch the resulting
-- IntegrityError and redirect to the existing owner instead of erroring.
CREATE UNIQUE INDEX IF NOT EXISTS idx_owners_phone_unique ON owners(phone) WHERE phone IS NOT NULL;

CREATE TABLE IF NOT EXISTS patients (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    animal_name TEXT,
    species TEXT,
    sex TEXT,
    age_note TEXT,
    repro_status TEXT,
    housing TEXT,
    notes TEXT,
    FOREIGN KEY (owner_id) REFERENCES owners(id)
);
CREATE INDEX IF NOT EXISTS idx_patients_owner ON patients(owner_id);

-- ============================================================ DISTRIBUTORS / PRICE LIST / INVENTORY
CREATE TABLE IF NOT EXISTS distributors (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    catalog_link TEXT,
    lead_time_days INTEGER,
    payment_terms TEXT,
    notes TEXT
);

-- Manual bookkeeping for what a distributor has billed you and what
-- you've paid them — a lump-sum charge per bill, payments recorded
-- against it, balance always computed (never stored). Not linked to
-- inventory, POS, or any report; every bill is a manual entry, same as
-- the paper/memory tracking this replaces.
CREATE TABLE IF NOT EXISTS distributor_bills (
    id TEXT PRIMARY KEY,                 -- allocated via next_id(db, "DB")
    distributor_id TEXT NOT NULL,
    bill_date DATE NOT NULL,
    bill_reference TEXT,                 -- the distributor's own paper/invoice number, optional
    total_amount NUMERIC(12,3) NOT NULL CHECK (total_amount >= 0),
    notes TEXT,
    created_at TEXT NOT NULL,
    created_by TEXT,
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_distbills_distributor ON distributor_bills(distributor_id);

CREATE TABLE IF NOT EXISTS distributor_bill_payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id TEXT NOT NULL,
    amount NUMERIC(12,3) NOT NULL CHECK (amount > 0),
    payment_date DATE NOT NULL,
    method TEXT,                         -- free text: 'Cash', 'Transfer', etc.
    notes TEXT,
    created_at TEXT NOT NULL,
    created_by TEXT,
    FOREIGN KEY (bill_id) REFERENCES distributor_bills(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_distbillpayments_bill ON distributor_bill_payments(bill_id);

-- Price List is declared further down (after inventory_list) so its
-- linked_item_id FK can be inline, rather than a forward reference to a
-- table that doesn't exist yet in this file.

-- Inventory Catalog: Medical / Retail
CREATE TABLE IF NOT EXISTS inventory_list (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Medical' CHECK (category IN ('Medical','Retail')),
    unit TEXT,
    track_expiry BOOLEAN NOT NULL DEFAULT TRUE,
    cost_price NUMERIC(12,3),
    distributor_id TEXT,
    -- 'Owned' (you bought this stock outright — the default) or
    -- 'Consignment' (a distributor's stock, sitting on your shelf; you
    -- owe them cost_price per unit only once it sells). Only meaningful
    -- for category='Retail' — enforced in app.py, not here. For a
    -- Consignment item, cost_price keeps its existing meaning (per-unit
    -- cost) but the *payee* changes: it's what's owed to distributor_id,
    -- not what the clinic itself paid — same column, same downstream
    -- COGS math, different real-world counterparty.
    ownership_type TEXT NOT NULL DEFAULT 'Owned' CHECK (ownership_type IN ('Owned','Consignment')),
    -- Set the moment this item most recently flipped Owned -> Consignment
    -- (app.py's consignment_items_bulk_edit). NULL if it's never been
    -- Consignment. consignment_balance() floors its sales/refund scan at
    -- this date per item, on top of the distributor-level period_start,
    -- so a sale from before the item was actually Consignment (e.g. years
    -- of prior Retail sales) never gets swept into what's owed.
    consignment_since TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    barcode TEXT UNIQUE,
    notes TEXT,
    FOREIGN KEY (distributor_id) REFERENCES distributors(id)
);

-- Price List: Service / Medicine / Retail
-- Medicine billing lines are priced by range and do NOT touch inventory stock.
-- Only Retail rows (optionally linked to an inventory item) are sold via POS and move stock.
CREATE TABLE IF NOT EXISTS price_list (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Service' CHECK (category IN ('Service','Medicine','Retail')),
    cost_price NUMERIC(12,3),
    sale_price NUMERIC(12,3),
    notes TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    linked_item_id TEXT,             -- Retail rows only: links to inventory_list.id for POS
    can_discount BOOLEAN NOT NULL DEFAULT FALSE,   -- if false, a bill containing this item can't have a discount applied
    FOREIGN KEY (linked_item_id) REFERENCES inventory_list(id)
);

-- ============================================================ AUDITS (whole-catalog Save/Confirm sessions)
-- One session = one shelf-walk. "Not Started Yet" is simply the absence of a session
-- for a date; a session becomes 'Confirmed' (locked, can't be edited) the moment the
-- user presses Confirm, otherwise it stays 'Draft' ("Saved") and can be resumed/edited.
-- Only Confirmed sessions count toward Inventory Status / Ordering Sheet history.
CREATE TABLE IF NOT EXISTS audit_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_date DATE NOT NULL,
    performed_by TEXT,
    status TEXT NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft','Confirmed')),
    created_at TEXT NOT NULL,
    confirmed_at TEXT,
    FOREIGN KEY (performed_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS audit_session_lines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL,
    item_id TEXT NOT NULL,
    stock_counted DOUBLE PRECISION,
    received_since_prior DOUBLE PRECISION NOT NULL DEFAULT 0,
    reorder_threshold DOUBLE PRECISION,          -- NULL = inherit from the last confirmed audit
    critical_item INTEGER,           -- NULL = inherit
    target_coverage_days DOUBLE PRECISION,       -- NULL = inherit
    nearest_expiry_date DATE,
    notes TEXT,
    FOREIGN KEY (session_id) REFERENCES audit_sessions(id),
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    -- One line per item per session — lets _save_audit_lines() use a
    -- single INSERT ... ON CONFLICT DO UPDATE instead of a
    -- check-then-insert, closing the race where two concurrent saves for
    -- the same item could both insert.
    UNIQUE (session_id, item_id)
);
CREATE INDEX IF NOT EXISTS idx_auditlines_session ON audit_session_lines(session_id);
CREATE INDEX IF NOT EXISTS idx_auditlines_item ON audit_session_lines(item_id);

-- Real-time stock movement — ONLY from POS Retail sales (not Medicine billing).
CREATE TABLE IF NOT EXISTS inventory_transactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT NOT NULL,
    change_qty DOUBLE PRECISION NOT NULL,
    reason TEXT NOT NULL,            -- 'sale' / 'manual_adjustment'
    ref_id TEXT,
    timestamp TEXT NOT NULL,
    user_id TEXT,
    FOREIGN KEY (item_id) REFERENCES inventory_list(id)
);
CREATE INDEX IF NOT EXISTS idx_invtxn_item ON inventory_transactions(item_id);

-- ============================================================ CONSIGNMENT
-- A distributor's stock sitting on your shelf — they're owed cost_price
-- per unit once it sells, you keep the markup. Consignment items are
-- ordinary Retail inventory_list rows (ownership_type='Consignment'), so
-- they already flow through pos_checkout / audit sessions / P&L exactly
-- like owned stock; these tables are the distributor-facing receiving/
-- shrinkage/returns/settlement layer on top of that shared data.
CREATE TABLE IF NOT EXISTS consignment_receipts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT NOT NULL,
    distributor_id TEXT NOT NULL,
    quantity NUMERIC(10,3) NOT NULL,
    unit_cost_at_receipt NUMERIC(12,3) NOT NULL,
    received_date DATE NOT NULL,
    delivery_reference TEXT,
    notes TEXT,
    received_by TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (received_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_consreceipts_item ON consignment_receipts(item_id);
CREATE INDEX IF NOT EXISTS idx_consreceipts_distributor ON consignment_receipts(distributor_id);

CREATE TABLE IF NOT EXISTS consignment_shrinkage (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT NOT NULL,
    distributor_id TEXT NOT NULL,
    quantity NUMERIC(10,3) NOT NULL,
    reason TEXT NOT NULL CHECK (reason IN ('Damaged','Expired','Other')),
    liable_party TEXT NOT NULL CHECK (liable_party IN ('Distributor','Clinic')),
    liability_overridden BOOLEAN NOT NULL DEFAULT FALSE,
    unit_cost NUMERIC(12,3) NOT NULL,
    notes TEXT,
    logged_by TEXT,
    logged_at TEXT NOT NULL,
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (logged_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_consshrinkage_item ON consignment_shrinkage(item_id);
CREATE INDEX IF NOT EXISTS idx_consshrinkage_distributor ON consignment_shrinkage(distributor_id);

CREATE TABLE IF NOT EXISTS consignment_returns (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT NOT NULL,
    distributor_id TEXT NOT NULL,
    quantity NUMERIC(10,3) NOT NULL,
    unit_cost_at_return NUMERIC(12,3) NOT NULL,
    return_date DATE NOT NULL,
    reason TEXT,
    notes TEXT,
    returned_by TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (returned_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_consreturns_item ON consignment_returns(item_id);
CREATE INDEX IF NOT EXISTS idx_consreturns_distributor ON consignment_returns(distributor_id);

CREATE TABLE IF NOT EXISTS consignment_settlements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distributor_id TEXT NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    amount_owed NUMERIC(12,3) NOT NULL,
    amount_paid NUMERIC(12,3) NOT NULL,
    payment_method TEXT,
    notes TEXT,
    settled_by TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (settled_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_conssettlements_distributor ON consignment_settlements(distributor_id);

-- ============================================================ VISITS (visit + wellness + grooming, one record)
CREATE TABLE IF NOT EXISTS visits (
    id TEXT PRIMARY KEY,
    patient_id TEXT NOT NULL,
    visit_type TEXT,                  -- 'Outpatient' / 'Inpatient'
    date DATE,
    doctor TEXT,                      -- free text, populated from a Vet-user dropdown on new entries
    weight_kg DOUBLE PRECISION,       -- patient's weight at this visit, in kilograms
    bcs INTEGER CHECK (bcs BETWEEN 1 AND 9),   -- Body Condition Score, 1-9 scale
    complaint TEXT,
    history TEXT,
    exam TEXT,
    treatment TEXT,
    case_status TEXT NOT NULL DEFAULT 'Needs Filling'
        CHECK (case_status IN ('Needs Filling','Ongoing','Admitted to Inpatient','Deceased/Euthanized',
                                'Lost to Follow Up','Resolved','Referred')),
    case_status_changed_at TEXT,      -- drives the 2-week "Lost to Follow Up" missed-flag clock
    updates_log TEXT,

    -- Follow-up (method, not type)
    followup_needed TEXT,             -- 'Y' / 'N'
    followup_method TEXT,             -- 'Physical Visit' / 'Phone Call'
    followup_reason TEXT,
    followup_date DATE,
    followup_status TEXT,             -- 'Pending' / 'Completed' / 'Cancelled' / 'N/A'

    -- Wellness reminder
    wellness_needed TEXT DEFAULT 'N',
    wellness_type TEXT,                -- 'Annual Vaccine' / 'Rabies Vaccine' / 'Deworming' / 'Spot On/Pill'
    wellness_next_dose_date DATE,
    wellness_contacted TEXT DEFAULT 'N',
    wellness_contact_method TEXT,      -- 'Phone Call' / 'Message'

    -- Grooming
    grooming_needed TEXT DEFAULT 'N',
    grooming_services TEXT,            -- comma-separated service names
    grooming_notes TEXT,
    grooming_admitted_items TEXT,
    grooming_status TEXT,              -- 'Waiting' / 'Ongoing' / 'Finished'
    grooming_contacted TEXT DEFAULT 'N',

    payment_status TEXT,               -- derived/display cache; real status computed from payments
    created_by TEXT,
    -- Set on every visit_edit() save — lets the edit form detect (and
    -- refuse to silently overwrite) a concurrent edit by someone else.
    updated_at TEXT,
    FOREIGN KEY (patient_id) REFERENCES patients(id)
);
CREATE INDEX IF NOT EXISTS idx_visits_patient ON visits(patient_id);
CREATE INDEX IF NOT EXISTS idx_visits_date ON visits(date);

-- Billing: Automatic (priced line items) OR Manual (single lump amount)
CREATE TABLE IF NOT EXISTS billing (
    visit_id TEXT PRIMARY KEY,
    billing_type TEXT NOT NULL DEFAULT 'Automatic' CHECK (billing_type IN ('Automatic','Manual')),
    -- codes column removed — Automatic billing is driven entirely by
    -- visit_billing_lines (price_id + quantity rows), not a comma string.
    manual_amount NUMERIC(12,3),               -- Manual: single lump sum, exported as one "Veterinary Services" line
    date_billed DATE,
    discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
    discount_applied_by TEXT,
    notes TEXT,
    -- The final payable figure for this bill (what compute_bill_totals()
    -- actually charges), kept in sync by logic.refresh_visit_billing_total()
    -- every time lines/discount/manual_amount change. Reports read this
    -- instead of re-deriving subtotal*(1-discount%) independently.
    total NUMERIC(12,3) NOT NULL DEFAULT 0,
    FOREIGN KEY (visit_id) REFERENCES visits(id)
);

-- Automatic visit billing's line items, snapshotted at Save time (search-
-- and-add billing UI in visit_detail.html) — this is what stops a later
-- Price List edit from retroactively changing what an already-billed
-- visit's bill (or that month's revenue/COGS report) says today.
CREATE TABLE IF NOT EXISTS visit_billing_lines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id TEXT NOT NULL,
    price_id TEXT NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    quantity NUMERIC(10,3) NOT NULL DEFAULT 1,
    unit_price NUMERIC(12,3) NOT NULL,
    unit_cost NUMERIC(12,3),
    created_at TEXT NOT NULL,
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (price_id) REFERENCES price_list(id)
);
CREATE INDEX IF NOT EXISTS idx_visitbillinglines_visit ON visit_billing_lines(visit_id);

-- payments is declared further down (after boarding_sessions/
-- inpatient_cases) so its FKs to both can be inline, rather than a
-- forward reference to a table that doesn't exist yet in this file.

-- ============================================================ BOARDING
-- Relies on the existing Patient/Owner records — a boarding session just
-- links to a patient_id, the same way a Visit or Inpatient case does.
CREATE TABLE IF NOT EXISTS boarding_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id TEXT NOT NULL,
    entry_date DATE NOT NULL,
    dismissal_date DATE,              -- expected/actual end date; editable if the stay is extended or shortened
    admitted_items TEXT,
    special_needs BOOLEAN NOT NULL DEFAULT FALSE,   -- chronic disease or custom requirement flag
    special_needs_notes TEXT,
    room TEXT,
    price_per_day NUMERIC(12,3),
    total NUMERIC(12,3),           -- raw subtotal (price_per_day * nights, or entered manually)
    -- 1 when `total` was auto-suggested (the Total field was left blank at
    -- create/edit time) rather than typed explicitly. While the stay is
    -- still active and this is 1, boarding_billing_summary() recomputes the
    -- subtotal live from price_per_day x nights-so-far instead of trusting
    -- this stale snapshot — but only when it's still the auto-suggested
    -- figure, so a deliberately-typed custom total is never silently
    -- overwritten.
    total_is_auto BOOLEAN NOT NULL DEFAULT TRUE,
    -- The persisted figure boarding_page()'s batched list view and any
    -- report read instead of recomputing per row — kept in sync by
    -- logic.refresh_boarding_total() every time the session is saved.
    billed_total NUMERIC(12,3),
    dismissed BOOLEAN NOT NULL DEFAULT FALSE,   -- has the animal actually left yet
    created_by TEXT,
    -- Set on every boarding_edit() save — lets the edit form detect (and
    -- refuse to silently overwrite) a concurrent edit by someone else.
    updated_at TEXT,
    FOREIGN KEY (patient_id) REFERENCES patients(id)
);
CREATE INDEX IF NOT EXISTS idx_boarding_patient ON boarding_sessions(patient_id);

-- "Something's Wrong!" incident log for a boarding stay
CREATE TABLE IF NOT EXISTS boarding_incidents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    boarding_id INTEGER NOT NULL,
    timestamp TEXT NOT NULL,
    issue TEXT NOT NULL,
    contacted TEXT NOT NULL DEFAULT 'N',        -- 'Y' / 'N'
    contact_method TEXT,                        -- 'Phone Call' / 'Text Message'
    response TEXT,
    user_id TEXT,
    FOREIGN KEY (boarding_id) REFERENCES boarding_sessions(id)
);
CREATE INDEX IF NOT EXISTS idx_boardingincidents_boarding ON boarding_incidents(boarding_id);

-- ============================================================ INPATIENT SYSTEM
CREATE TABLE IF NOT EXISTS inpatient_cases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id TEXT NOT NULL,
    visit_id TEXT,
    complaint TEXT,
    exam_findings TEXT,
    weight_kg DOUBLE PRECISION,       -- patient's weight at admission, in kilograms
    bcs INTEGER CHECK (bcs BETWEEN 1 AND 9),   -- Body Condition Score, 1-9 scale
    admission_date DATE NOT NULL,
    admitted_items TEXT,
    dismissed BOOLEAN NOT NULL DEFAULT FALSE,
    dismissal_date DATE,
    attending_vet_id TEXT,
    supervising_vet_id TEXT,
    discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
    discount_applied_by TEXT,
    created_by TEXT,
    -- The final payable figure for this case (what compute_bill_totals()
    -- actually charges), kept in sync by logic.refresh_inpatient_total()
    -- every time procedures/discount change.
    total NUMERIC(12,3) NOT NULL DEFAULT 0,
    -- Set on every inpatient_edit() save — lets the edit form detect (and
    -- refuse to silently overwrite) a concurrent edit by someone else.
    updated_at TEXT,
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (attending_vet_id) REFERENCES users(id),
    FOREIGN KEY (supervising_vet_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_inpatient_patient ON inpatient_cases(patient_id);

CREATE TABLE IF NOT EXISTS payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id TEXT,
    inpatient_case_id INTEGER,
    boarding_id INTEGER,
    amount NUMERIC(12,3) NOT NULL,
    method TEXT,
    date DATE NOT NULL,
    user_id TEXT,
    notes TEXT,
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (inpatient_case_id) REFERENCES inpatient_cases(id),
    FOREIGN KEY (boarding_id) REFERENCES boarding_sessions(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_payments_visit ON payments(visit_id);
CREATE INDEX IF NOT EXISTS idx_payments_case ON payments(inpatient_case_id);
CREATE INDEX IF NOT EXISTS idx_payments_boarding ON payments(boarding_id);

CREATE TABLE IF NOT EXISTS inpatient_updates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id INTEGER NOT NULL,
    timestamp TEXT NOT NULL,
    note TEXT NOT NULL,
    user_id TEXT,
    FOREIGN KEY (case_id) REFERENCES inpatient_cases(id)
);
CREATE INDEX IF NOT EXISTS idx_inpupdates_case ON inpatient_updates(case_id);

CREATE TABLE IF NOT EXISTS inpatient_contact_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id INTEGER NOT NULL,
    timestamp TEXT NOT NULL,
    picked_up INTEGER NOT NULL,
    staff_user_id TEXT,
    notes TEXT,
    FOREIGN KEY (case_id) REFERENCES inpatient_cases(id)
);
CREATE INDEX IF NOT EXISTS idx_inpcontact_case ON inpatient_contact_log(case_id);

CREATE TABLE IF NOT EXISTS inpatient_billing (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id INTEGER NOT NULL,
    price_id TEXT NOT NULL,
    quantity NUMERIC(10,3) NOT NULL DEFAULT 1,
    -- Price/cost snapshotted at the moment this line was added — so a
    -- later Price List edit can't retroactively change what an
    -- already-billed stay owes, or this month's revenue/COGS report for
    -- an already-logged procedure. unit_cost stays nullable: not every
    -- price_list row necessarily has a cost_price set (Services
    -- typically don't carry a COGS basis).
    unit_price NUMERIC(12,3),
    unit_cost NUMERIC(12,3),
    logged_by TEXT,
    timestamp TEXT NOT NULL,
    FOREIGN KEY (case_id) REFERENCES inpatient_cases(id),
    FOREIGN KEY (price_id) REFERENCES price_list(id)
);
CREATE INDEX IF NOT EXISTS idx_inpbilling_case ON inpatient_billing(case_id);

-- ============================================================ FILE ATTACHMENTS
CREATE TABLE IF NOT EXISTS attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id TEXT NOT NULL,
    visit_id TEXT,
    inpatient_case_id INTEGER,
    relative_path TEXT NOT NULL,
    original_name TEXT NOT NULL,
    uploaded_at TEXT NOT NULL,
    uploaded_by TEXT,
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (inpatient_case_id) REFERENCES inpatient_cases(id),
    FOREIGN KEY (uploaded_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_attach_patient ON attachments(patient_id);
CREATE INDEX IF NOT EXISTS idx_attach_visit ON attachments(visit_id);
CREATE INDEX IF NOT EXISTS idx_attach_case ON attachments(inpatient_case_id);

-- ============================================================ POINT OF SALE (Retail only)
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_date TEXT NOT NULL,  -- actually a full timestamp (datetime.now().isoformat()), not date-only -- see note in data_integrity_framework.md
    cashier_id TEXT,
    subtotal NUMERIC(12,3) NOT NULL,
    discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
    discount_applied_by TEXT,
    total NUMERIC(12,3) NOT NULL,
    payment_method TEXT,
    -- Cash payment method only — what the customer actually handed over
    -- and what was handed back, for the cashier's own reconciliation.
    -- Optional: NULL for non-cash sales, and NULL for cash too if the
    -- cashier didn't bother entering it.
    cash_received NUMERIC(12,3),
    change_given NUMERIC(12,3),
    -- One-time token generated fresh each time the POS page loads (see
    -- pos_page()/pos.html), submitted back with the checkout POST. A
    -- double-click ("Complete Sale" clicked twice on the same unchanged
    -- cart) previously created two separate, fully valid sales — no
    -- confirmation prompt either side, nothing tying the two submissions
    -- together. pos_checkout() checks for an existing sale with this key
    -- before inserting a new one; NULL for any sale that predates this
    -- column (never collides — see idx_sales_idempotency_key below).
    idempotency_key TEXT,
    FOREIGN KEY (cashier_id) REFERENCES users(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sales_idempotency_key ON sales(idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS sale_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INTEGER NOT NULL,
    item_id TEXT NOT NULL,
    quantity NUMERIC(10,3) NOT NULL,
    unit_price NUMERIC(12,3) NOT NULL,
    line_total NUMERIC(12,3) NOT NULL,
    -- Cost snapshotted at sale time — this is what lets COGS reporting
    -- reflect the actual cost basis of each sale instead of re-reading
    -- current inventory cost (which would retroactively change a past
    -- month's COGS every time an item's cost is edited). Nullable: an
    -- item without a cost_price set has nothing to snapshot.
    unit_cost NUMERIC(12,3),
    FOREIGN KEY (sale_id) REFERENCES sales(id),
    FOREIGN KEY (item_id) REFERENCES inventory_list(id)
);
CREATE INDEX IF NOT EXISTS idx_saleitems_sale ON sale_items(sale_id);

-- ============================================================ REFUNDS (Admin only)
-- Two kinds: 'retail' (one or more products returned, identified by barcode,
-- with an option to put the stock back) and 'service' (a straight revenue
-- reduction against a Visit or Inpatient case, no stock impact). Both reduce
-- revenue in the P&L for the month the refund itself was processed in —
-- not the original sale/visit's month — matching normal accounting practice.
CREATE TABLE IF NOT EXISTS refunds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_type TEXT NOT NULL CHECK (refund_type IN ('retail','service')),
    refund_date DATE NOT NULL,
    amount NUMERIC(12,3) NOT NULL,
    restocked BOOLEAN NOT NULL DEFAULT FALSE,   -- retail only: were the returned items put back into inventory?
    -- Retail only — which POS sale this refund is against. Required at
    -- the app layer (refund_retail_save() in app.py) so a retail refund
    -- can never be recorded against an item that was never actually
    -- sold, or for more than was sold minus what's already been
    -- refunded — see refund_items.sale_item_id for the per-line
    -- quantity/price tie-back.
    sale_id INTEGER,
    visit_id TEXT,                          -- service only, optional link
    inpatient_case_id INTEGER,              -- service only, optional link
    reason TEXT,
    -- How the money was actually handed back — 'Cash', 'Card', or
    -- 'Transfer' (same vocabulary as sales.payment_method). Not
    -- necessarily the same method the original sale/payment used; Cash
    -- Register needs this to know which bucket to subtract a refund from.
    refund_method TEXT,
    processed_by TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (sale_id) REFERENCES sales(id),
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (inpatient_case_id) REFERENCES inpatient_cases(id)
);
CREATE INDEX IF NOT EXISTS idx_refunds_date ON refunds(refund_date);
CREATE INDEX IF NOT EXISTS idx_refunds_sale ON refunds(sale_id);

CREATE TABLE IF NOT EXISTS refund_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id INTEGER NOT NULL,
    item_id TEXT NOT NULL,
    quantity NUMERIC(10,3) NOT NULL,
    unit_price NUMERIC(12,3) NOT NULL,
    line_total NUMERIC(12,3) NOT NULL,
    -- The specific sale_items row this line is refunding against — lets
    -- refund_retail_save() price from what was actually charged (not
    -- today's Price List price) and sum prior refunds against this exact
    -- line to enforce a refund can never exceed what was actually sold.
    sale_item_id INTEGER,
    FOREIGN KEY (refund_id) REFERENCES refunds(id),
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    FOREIGN KEY (sale_item_id) REFERENCES sale_items(id)
);
CREATE INDEX IF NOT EXISTS idx_refunditems_refund ON refund_items(refund_id);

-- ============================================================ CASH REGISTER
-- Unifies every place money actually changes hands on a given day (POS
-- sales, Visit/Inpatient/Boarding payments, and refunds netted as
-- negative) for end-of-day cash-up against what's physically in the till.
CREATE TABLE IF NOT EXISTS cash_register_payouts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payout_date DATE NOT NULL,
    amount NUMERIC(12,3) NOT NULL,
    reason TEXT NOT NULL,
    logged_by TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (logged_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_cashpayouts_date ON cash_register_payouts(payout_date);

-- One immutable historical entry per audit — a re-audit of the same day
-- adds a new row rather than overwriting the old one.
CREATE TABLE IF NOT EXISTS cash_register_audits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_date DATE NOT NULL,
    system_cash NUMERIC(12,3) NOT NULL,
    system_card NUMERIC(12,3) NOT NULL,
    system_transfer NUMERIC(12,3) NOT NULL,
    counted_cash NUMERIC(12,3) NOT NULL,
    difference NUMERIC(12,3) NOT NULL,      -- counted_cash - system_cash
    status TEXT NOT NULL CHECK (status IN ('Deficit','Surplus','Perfect')),
    notes TEXT,
    performed_by TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (performed_by) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_cashaudits_date ON cash_register_audits(audit_date);

-- ============================================================ OPEX / P&L (monthly is the source; yearly rolls it up)
CREATE TABLE IF NOT EXISTS monthly_opex (
    month TEXT PRIMARY KEY,           -- 'YYYY-MM'
    rent NUMERIC(12,3) NOT NULL DEFAULT 0,
    salaries NUMERIC(12,3) NOT NULL DEFAULT 0,
    utilities NUMERIC(12,3) NOT NULL DEFAULT 0,
    marketing NUMERIC(12,3) NOT NULL DEFAULT 0,
    other NUMERIC(12,3) NOT NULL DEFAULT 0
);

-- Materialized per-month revenue/COGS, kept in sync incrementally by app.py
-- on every write that affects it (new sale, billing, refund, boarding total,
-- inpatient billing/discount, etc.) and fully rebuilt by
-- logic.recompute_full_summary() whenever a shared Price List / Inventory
-- Catalog cost or sale price changes, since those can retroactively affect
-- COGS/revenue for many past months at once. This is what lets Monthly &
-- Yearly P&L load instantly regardless of how many historical
-- billing/sales/refund rows exist, instead of re-scanning all of them on
-- every page view.
CREATE TABLE IF NOT EXISTS monthly_financial_summary (
    month TEXT PRIMARY KEY,           -- 'YYYY-MM'
    revenue NUMERIC(12,3) NOT NULL DEFAULT 0,
    cogs NUMERIC(12,3) NOT NULL DEFAULT 0,
    updated_at TEXT
);

-- ============================================================ APPOINTMENTS
-- Slot grid is generated dynamically from settings (appt_start_time / appt_end_time /
-- appt_slot_minutes) — no fixed slot table needed; slot labels (each slot's own start
-- time, e.g. '09:00', '09:30'...) are derived at render time from that range.
CREATE TABLE IF NOT EXISTS appointments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appt_date DATE NOT NULL,
    slot_label TEXT NOT NULL,          -- the slot's start time, e.g. '09:00', '09:30'...
    resource_type TEXT NOT NULL CHECK (resource_type IN ('vet','grooming')),
    resource_id TEXT,                  -- users.id when resource_type='vet'; NULL for grooming
    pet_name TEXT NOT NULL,
    owner_name TEXT NOT NULL,
    appointment_type TEXT NOT NULL CHECK (appointment_type IN ('Medical','Grooming')),
    reason TEXT,
    created_by TEXT,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_appt_date ON appointments(appt_date);

-- Enforces at the database level what logic.slot_conflict() only checks at
-- the application level: two appointments can't occupy the same slot for
-- the same vet/groomer. The app-level check-then-insert alone has a race
-- window — two concurrent bookings for the same slot can both pass the
-- check before either inserts. COALESCE(resource_id, '') is needed because
-- resource_id is NULL for grooming rows, and Postgres otherwise treats
-- every NULL as distinct (so two grooming rows for the same slot would
-- never actually collide on a plain (appt_date, slot_label, resource_type,
-- resource_id) unique index).
CREATE UNIQUE INDEX IF NOT EXISTS uq_appointments_slot
    ON appointments (appt_date, slot_label, resource_type, COALESCE(resource_id, ''));

